### ISSUE TITLE
Allow repeated rules in CSS, without vendor prefix too.

### ISSUE THREAD

**Issue by bic-ed** [gpbmike/refresh-sf#22]
For instance, according to http://caniuse.com/#search=calc, calc() is not supported by old android browsers, Opera mini and others, so one might need a fall back for margin, width, etc.. when using calc(), writing a code like this:
```css
#content-right {
  /* not supporting calc() */
  width: 97%;
  margin-right: 1.5%;
  /* supporting calc() */
  width: calc(100% - 12px);
  margin-right: calc(0% + 6px);
}
```
since it makes no sense to use a vendor prefix in a code like the above.
If there is already an option for it forgive me, because I didn't find it and I apologize in advance.
